org.gradle.jvmargs=-Xmx6G
org.gradle.daemon=true
org.gradle.caching=true
org.gradle.parallel=true

mod_id=litematica-printer-autyism
mod_name=Litematica Printer Autyism Edition
mod_version=1.0.0
maven_group=com.autyism.printer
archives_base_name=litematica-printer-autyism

minecraft_version=1.21.11
loader_version=0.19.3
fabric_version=0.140.2+1.21.11
malilib=malilib-fabric-1.21.11:0.27.20
litematica=litematica-fabric-1.21.11:0.26.16
modmenu=17.0.0
pinyin_version=2.5.1
lombok_version=1.18.42
remote_inventory_version=1.0.2
